name: Supabase Keep Alive

on:
  schedule:
    # Jalan setiap hari jam 07:00 WIB (00:00 UTC)
    - cron: "0 0 * * *"
  workflow_dispatch: # Biar bisa kita klik tombol 'Run' manual buat ngetes

jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase URL
        run: |
          # Melakukan request ringan ke tabel 'announcements'
          curl -f -X GET '${{ secrets.SUPABASE_URL }}/rest/v1/announcements?select=*&limit=1' \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"
